### ISSUE TITLE
可以作为iOS的调试工具么

### ISSUE THREAD

**Issue by sequencer** [hypoyao/HttpMock#1]
看到您是中国人...就用中文了
最近在尝试修改iOS app的发包
需要有以下的功能
接收到packet的response的一部分替换发出packet的sent的一部分
实时修改接收包
在mac上可以使用代理实现
然而在ios上有办法直接实现么(越狱环境)

**Comment by hypoyao** [comment]
GYHttpMock只能作为iOS App HTTP Developer Library。
如果你是需要一个第三方工具来修改HTTP Response的话，其实也是可以通过代理抓包工具（如Charles）实现的。

**Comment by sequencer** [comment]
@hypoyao 我现在就在用Charles 但是没API 所以没法实现复杂的功能.
这个只能针对某一个应用抓包还是能对系统抓包?
貌似用作在ios9用作代理可以对系统抓包咧

**Comment by hypoyao** [comment]
这个只能针对某个应用，是解决App开发过程中改包的问题

**Comment by sequencer** [comment]
@hypoyao 好吧 还是谢谢你了!
能问一下您是否知道有类似的工具提供了?

**Comment by hypoyao** [comment]
暂时还不知道，可以研究一下，如果你发现有这种方法，也请告知一下，谢谢！
