### ISSUE TITLE
示例crash了

### ISSUE THREAD

**Issue by CocoaDebug** [hypoyao/HttpMock#6]
我按照示例:
mockRequest(@"GET", @"(._?)google.com(._?)".regex).
withBody(@"{\"name\":\"abc\"}".regex);

一跑起来就crash:
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid regex pattern: {"name":"abc"}
Error: Error Domain=NSCocoaErrorDomain Code=2048 "The value “{"name":"abc"}” is invalid." UserInfo={NSInvalidValue={"name":"abc"}}'

**Comment by hypoyao** [comment]
感谢反馈！第一示例确实有问题，已经修改了。
